### ISSUE TITLE
Unable to start django

### ISSUE THREAD

**Issue by dennislabajo** [sclorg/django-ex#143]
Hello - I just tried deploying this to OpenShift and could not get the django pod to start up.  The postgresql has no issues.   Any ideas what may be causing this?  Thanks.

```
NAME                             READY     STATUS             RESTARTS   AGE
django-psql-persistent-1-build   0/1       Completed          0          26m
django-psql-persistent-1-jtg64   0/1       CrashLoopBackOff   7          18m
postgresql-1-cqlp2               1/1       Running            0          26m
```

This is the error from the logs.

```

---> Migrating database ...
--
  | Operations to perform:
  | Apply all migrations: admin, auth, contenttypes, sessions, welcome
  | Running migrations:
  | No migrations to apply.
  | ---> Serving application with gunicorn (wsgi) ...
  | [2019-08-28 18:18:09 +0000] [1] [INFO] Starting gunicorn 19.4.5
  | [2019-08-28 18:18:09 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080  (1)
  | [2019-08-28 18:18:09 +0000] [1] [INFO] Using worker: sync
  | [2019-08-28 18:18:09 +0000] [41] [INFO] Booting worker with pid: 41
  | [2019-08-28 18:18:10 +0000] [42] [INFO] Booting worker with pid: 42
  | [2019-08-28 18:18:10 +0000] [43] [INFO] Booting worker with pid: 43
  | [2019-08-28 18:18:10 +0000] [45] [INFO] Booting worker with pid: 45
  | [2019-08-28 18:18:10 +0000] [44] [INFO] Booting worker with pid: 44
  | [2019-08-28 18:18:11 +0000] [46] [INFO] Booting worker with pid: 46
  | [2019-08-28 18:18:11 +0000] [47] [INFO] Booting worker with pid: 47
  | [2019-08-28 18:18:12 +0000] [49] [INFO] Booting worker with pid: 49
  | [2019-08-28 18:18:12 +0000] [48] [INFO] Booting worker with pid: 48
  | [2019-08-28 18:18:12 +0000] [51] [INFO] Booting worker with pid: 51
  | [2019-08-28 18:18:13 +0000] [50] [INFO] Booting worker with pid: 50
  | [2019-08-28 18:18:40 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:41)
  | [2019-08-28 18:18:40 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:42)
  | [2019-08-28 18:18:40 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:43)
  | [2019-08-28 18:18:40 +0000] [1] [INFO] Handling signal: term
  | [2019-08-28 18:18:40 +0000] [42] [INFO] Worker exiting (pid: 42)
  | [2019-08-28 18:18:41 +0000] [41] [ERROR] Exception in worker process:
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/workers/base.py", line 176, in handle_abort
  | sys.exit(1)
  | SystemExit: 1
  |  
  | The above exception was the direct cause of the following exception:
  |  
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
  | worker.init_process()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/workers/base.py", line 122, in init_process
  | self.load_wsgi()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
  | self.wsgi = self.app.wsgi()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
  | self.callable = self.load()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
  | return self.load_wsgiapp()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
  | return util.import_app(self.app_uri)
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/util.py", line 357, in import_app
  | __import__(module)
  | File "/opt/app-root/src/wsgi.py", line 16, in <module>
  | application = get_wsgi_application()
  | File "/opt/app-root/lib/python3.6/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
  | django.setup(set_prefix=False)
  | File "/opt/app-root/lib/python3.6/site-packages/django/__init__.py", line 20, in setup
  | from django.utils.log import configure_logging
  | File "/opt/app-root/lib/python3.6/site-packages/django/utils/log.py", line 8, in <module>
  | from django.core import mail
  | File "/opt/app-root/lib/python3.6/site-packages/django/core/mail/__init__.py", line 11, in <module>
  | from django.core.mail.message import (
  | File "/opt/app-root/lib/python3.6/site-packages/django/core/mail/message.py", line 12, in <module>
  | from email.mime.base import MIMEBase
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/email/mime/base.py", line 9, in <module>
  | import email.policy
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/email/policy.py", line 9, in <module>
  | from email.contentmanager import raw_data_manager
  | File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  | File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked
  | File "<frozen importlib._bootstrap>", line 894, in _find_spec
  | File "<frozen importlib._bootstrap_external>", line 1157, in find_spec
  | File "<frozen importlib._bootstrap_external>", line 1129, in _get_spec
  | File "<frozen importlib._bootstrap_external>", line 1271, in find_spec
  | File "<frozen importlib._bootstrap_external>", line 96, in _path_isfile
  | File "<frozen importlib._bootstrap_external>", line 88, in _path_is_mode_type
  | File "<frozen importlib._bootstrap_external>", line 82, in _path_stat
  | SystemError: PyEval_EvalFrameEx returned a result with an error set
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/workers/base.py", line 176, in handle_abort
  | sys.exit(1)
  | SystemExit: 1
  |  
  | The above exception was the direct cause of the following exception:
  |  
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
  | worker.init_process()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/workers/base.py", line 122, in init_process
  | self.load_wsgi()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
  | self.wsgi = self.app.wsgi()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
  | self.callable = self.load()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
  | return self.load_wsgiapp()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
  | return util.import_app(self.app_uri)
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/util.py", line 357, in import_app
  | __import__(module)
  | File "/opt/app-root/src/wsgi.py", line 16, in <module>
  | application = get_wsgi_application()
  | File "/opt/app-root/lib/python3.6/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
  | django.setup(set_prefix=False)
  | File "/opt/app-root/lib/python3.6/site-packages/django/__init__.py", line 20, in setup
  | from django.utils.log import configure_logging
  | File "/opt/app-root/lib/python3.6/site-packages/django/utils/log.py", line 8, in <module>
  | from django.core import mail
  | File "/opt/app-root/lib/python3.6/site-packages/django/core/mail/__init__.py", line 11, in <module>
  | from django.core.mail.message import (
  | File "/opt/app-root/lib/python3.6/site-packages/django/core/mail/message.py", line 12, in <module>
  | from email.mime.base import MIMEBase
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/email/mime/base.py", line 9, in <module>
  | import email.policy
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/email/policy.py", line 9, in <module>
  | from email.contentmanager import raw_data_manager
  | File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  | File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked
  | File "<frozen importlib._bootstrap>", line 894, in _find_spec
  | File "<frozen importlib._bootstrap_external>", line 1157, in find_spec
  | File "<frozen importlib._bootstrap_external>", line 1129, in _get_spec
  | File "<frozen importlib._bootstrap_external>", line 1271, in find_spec
  | File "<frozen importlib._bootstrap_external>", line 96, in _path_isfile
  | File "<frozen importlib._bootstrap_external>", line 88, in _path_is_mode_type
  | File "<frozen importlib._bootstrap_external>", line 82, in _path_stat
  | SystemError: PyEval_EvalFrameEx returned a result with an error set
  | [2019-08-28 18:18:41 +0000] [41] [INFO] Worker exiting (pid: 41)
  | [2019-08-28 18:18:42 +0000] [43] [ERROR] Exception in worker process:
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
  | worker.init_process()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/workers/base.py", line 122, in init_process
  | self.load_wsgi()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
  | self.wsgi = self.app.wsgi()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
  | self.callable = self.load()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
  | return self.load_wsgiapp()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
  | return util.import_app(self.app_uri)
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/util.py", line 357, in import_app
  | __import__(module)
  | File "/opt/app-root/src/wsgi.py", line 16, in <module>
  | application = get_wsgi_application()
  | File "/opt/app-root/lib/python3.6/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
  | django.setup(set_prefix=False)
  | File "/opt/app-root/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
  | apps.populate(settings.INSTALLED_APPS)
  | File "/opt/app-root/lib/python3.6/site-packages/django/apps/registry.py", line 108, in populate
  | app_config.import_models()
  | File "/opt/app-root/lib/python3.6/site-packages/django/apps/config.py", line 202, in import_models
  | self.models_module = import_module(models_module_name)
  | File "/opt/app-root/lib64/python3.6/importlib/__init__.py", line 126, in import_module
  | return _bootstrap._gcd_import(name[level:], package, level)
  | File "/opt/app-root/lib/python3.6/site-packages/django/contrib/auth/models.py", line 4, in <module>
  | from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  | File "/opt/app-root/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 52, in <module>
  | class AbstractBaseUser(models.Model):
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/base.py", line 124, in __new__
  | new_class.add_to_class('_meta', Options(meta, app_label))
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/base.py", line 325, in add_to_class
  | value.contribute_to_class(cls, name)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/options.py", line 214, in contribute_to_class
  | self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/__init__.py", line 33, in __getattr__
  | return getattr(connections[DEFAULT_DB_ALIAS], item)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/utils.py", line 211, in __getitem__
  | backend = load_backend(db['ENGINE'])
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/utils.py", line 115, in load_backend
  | return import_module('%s.base' % backend_name)
  | File "/opt/app-root/lib64/python3.6/importlib/__init__.py", line 126, in import_module
  | return _bootstrap._gcd_import(name[level:], package, level)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 21, in <module>
  | import psycopg2 as Database
  | File "/opt/app-root/lib/python3.6/site-packages/psycopg2/__init__.py", line 50, in <module>
  | from psycopg2._psycopg import (                     # noqa
  | SystemError: initialization of _psycopg raised unreported exception
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
  | worker.init_process()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/workers/base.py", line 122, in init_process
  | self.load_wsgi()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
  | self.wsgi = self.app.wsgi()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
  | self.callable = self.load()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
  | return self.load_wsgiapp()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
  | return util.import_app(self.app_uri)
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/util.py", line 357, in import_app
  | __import__(module)
  | File "/opt/app-root/src/wsgi.py", line 16, in <module>
  | application = get_wsgi_application()
  | File "/opt/app-root/lib/python3.6/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
  | django.setup(set_prefix=False)
  | File "/opt/app-root/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
  | apps.populate(settings.INSTALLED_APPS)
  | File "/opt/app-root/lib/python3.6/site-packages/django/apps/registry.py", line 108, in populate
  | app_config.import_models()
  | File "/opt/app-root/lib/python3.6/site-packages/django/apps/config.py", line 202, in import_models
  | self.models_module = import_module(models_module_name)
  | File "/opt/app-root/lib64/python3.6/importlib/__init__.py", line 126, in import_module
  | return _bootstrap._gcd_import(name[level:], package, level)
  | File "/opt/app-root/lib/python3.6/site-packages/django/contrib/auth/models.py", line 4, in <module>
  | from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  | File "/opt/app-root/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 52, in <module>
  | class AbstractBaseUser(models.Model):
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/base.py", line 124, in __new__
  | new_class.add_to_class('_meta', Options(meta, app_label))
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/base.py", line 325, in add_to_class
  | value.contribute_to_class(cls, name)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/models/options.py", line 214, in contribute_to_class
  | self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/__init__.py", line 33, in __getattr__
  | return getattr(connections[DEFAULT_DB_ALIAS], item)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/utils.py", line 211, in __getitem__
  | backend = load_backend(db['ENGINE'])
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/utils.py", line 115, in load_backend
  | return import_module('%s.base' % backend_name)
  | File "/opt/app-root/lib64/python3.6/importlib/__init__.py", line 126, in import_module
  | return _bootstrap._gcd_import(name[level:], package, level)
  | File "/opt/app-root/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 21, in <module>
  | import psycopg2 as Database
  | File "/opt/app-root/lib/python3.6/site-packages/psycopg2/__init__.py", line 50, in <module>
  | from psycopg2._psycopg import (                     # noqa
  | SystemError: initialization of _psycopg raised unreported exception
  | [2019-08-28 18:18:42 +0000] [43] [INFO] Worker exiting (pid: 43)
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/arbiter.py", line 199, in run
  | handler()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/arbiter.py", line 234, in handle_term
  | raise StopIteration
  | StopIteration
  |  
  | During handling of the above exception, another exception occurred:
  |  
  | Traceback (most recent call last):
  | File "/opt/app-root/bin/gunicorn", line 11, in <module>
  | sys.exit(run())
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
  | WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/app/base.py", line 192, in run
  | super(Application, self).run()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/app/base.py", line 72, in run
  | Arbiter(self).run()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/arbiter.py", line 202, in run
  | self.halt()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/arbiter.py", line 302, in halt
  | self.stop()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/arbiter.py", line 347, in stop
  | time.sleep(0.1)
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/arbiter.py", line 219, in handle_chld
  | self.reap_workers()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/arbiter.py", line 464, in reap_workers
  | raise HaltServer(reason, self.WORKER_BOOT_ERROR)
  | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>


```

**Comment by frenzymadness** [comment]
Hello. Sorry for the delay. Have you figured this up or is this still relevant?

**Comment by dennislabajo** [comment]
Hi @frenzymadness - No worries.  This can be closed. It is no longer relevant.  Thanks.
